### ISSUE TITLE
SparkSession not closed

### ISSUE THREAD

**Issue by LorePat93** [ssavvides/tpch-spark#8]
The SparkSession is not closed after the end of all jobs. This causes Kubernetes executions not to end the executors and driver pods.

Fix: add spark.close() at line 106 in /src/main/scala/TpchQuery.scala

**Comment by ssavvides** [comment]
Thank you! This should be fixed in https://github.com/ssavvides/tpch-spark/commit/b93b7fc6e1b09fc1f1f1de301c56aee954382c75

**Comment by LorePat93** [comment]
Thank you!
The spark.close() function should be done in any execution, also if them fails.
So, it is better to surround the code with `try {execute queries}` `catch {print some Exception info} `and then `finally { spark.close() }`
